### ISSUE TITLE
CLI Init errors

### ISSUE THREAD

**Issue by roomman** [CleverStack/cleverstack-cli#65]
Hi, I've been trying to get a "clever init web-app" command to work for the last few days. I'm attempting it on a new Macbook Pro with Command Line Tools installed. This is my first time using CleverStack. I've been using Yoeman and Ember-cli without any issues. Other projects are using Bower and Grunt without problems. 

I've read various support notes on here and StackFlow but can't seem to get to the bottom of it. In no particular order (indeed, I've tired several times in different orders) here's what I've done:
- Reinstalled Node / NPM
- Installed Bower
- Installed Grunt
- Installed cleverstack-cli
- Cleared NPM cache
- Cleared Bower cache
- Ensured correct permissions on $PATH folders
- Tried running "clever init web-app -f"
- Tried running the command from various locations

Each time I run the command I'm getting stuck at the same point: installing NPM modules (see below). Any suggestions? Many thanks in advance.

```
Preparing for installation...
-----------------------------
args             = []
--force          = undefined
project          = "my-app"
projectFolder    = "/Users/simon/Sites/my-app"
singleSeed       = false
installFrontend  = true
installBackend   = true
-----------------------------
  ├── Creating project installation path...
  ├── Creating installation path /Users/simon/Sites/my-app...
  └── Preparing seed installation list...

Installing Backend...
  ├── Installation path is /Users/simon/Sites/my-app/backend...ading...   ┊   St  ├── Downloading and extracting node-seed...                                   

  ├── Creating local configuration file config/local.json...
  ├── Installing NPM modules...rogress: [▒---------]  7 %   ┊   Installing: Back

 Status @ 5s |   Installation Progress: [▒▒--------]  21 %   ┊   Installing: Backend   ┊   Step: Installing NPM modules...   ┊   Step Time: 1s   ┊       
```

**Comment by roomman** [comment]
I should add that the only error I am getting is this one, when I install cleverstack-cli:
```
npm WARN engine cleverstack-cli@1.2.3: wanted: {"node":">=0.10 <=0.12","npm":">=1.4 <=2.5"} (current: {"node":"0.12.2","npm":"2.7.4"})
```

**Comment by pilsy** [comment]
Hi @roomman sorry to hear your having troubles, the log message you pasted unfortunately doesn't help much.

Recently there have been issues with github (getting DDOS'ed), with bower (their registry going down) and NPM (probably because of the ddos as well). That may have been the problem last weekend and week - but that's definitely not the case if it's not working now.

I would start by clearing your NPM cache (`rm -rf ~/.npm/`) or `npm cache clean` - then run `clever init my-project backend -f -v` and see what that produces...

**Comment by roomman** [comment]
Hi @pilsy and thanks for getting back to me. I've tried that but it's hanging at the same point, although:
```
Status @ 4s |   Installation Progress: [▒▒▒▒▒-----]  50 %   ┊   Installing: Backend   ┊   Step: Installing NPM modules...   ┊   Step Time: 1s   ┊
```
So making some progress.

Clearly I have an issue with NPM. I'll investigate further but if you have any bright ideas please shout.

Many thanks.

**Comment by pilsy** [comment]
I would try cloning https://github.com/CleverStack/node-seed into a folder, then run `clever setup -v` that should be more helpful - also if clever setup doesn't work i would try doing `npm i`

**Comment by pilsy** [comment]
I'm thinking that i fixed these issues with the release of https://github.com/CleverStack/cleverstack-cli/releases/tag/1.2.5 and the latest versions of clever-auth, clever-users, clever-roles and clever-accounts.

Because module dependencies are enabled again using peerDependencies, on node >= 0.8 (including iojs) things install correctly.

`clever init my-app clever-orm clever-users` - will install clever-orm, clever-auth, clever-accounts, clever-roles and clever-users.

**Comment by pilsy** [comment]
Please re-open the issue if your issues with cleverstack-cli continue

**Comment by scfox** [comment]
I am having identical issue to roomman:
clever init cs12 -f 
freezes at either 7% or 21% of backend installation.  I am using clever version 1.2.7.  I've tried:
bower cache clean
npm cache clean
sudo rm -rf ~/.npm
I've also tried running clever command with sudo and reinstalling clever, bower, and npm.
All same results:

Preparing for installation...
  └── Creating project installation path...

Installing Backend...
  ├── Installation path is .../cs12/backend...ding...   ┊   Step Time: 1s   ┊Downloading and extracting node-seed...                                                                               


 Status @ 3s |   Installation Progress: [▒---------]  7 %   ┊   Installing: Backend   ┊   Step: Downloading and extracting node-seed...   ┊   Step Time: 2s   ┊
